### ISSUE TITLE
Broken building in Cython >= 3.0.0

### ISSUE THREAD

**Issue by martinbenes1996** [dwgoon/jpegio#25]
On some platforms, source distribution build fails. This is because Cython does not handle well `const` attributes ([ref](https://stackoverflow.com/a/23875037/20225232)). In jpegio `const` attributes are present in clibjpeg.pxd.

The bug appearing only now is related to Cython 3 released earlier this week.
See the error log from [this CI pipeline](https://github.com/martinbenes1996/jpeglib/actions/runs/5596941268).

I managed to fix it by removing the `const` declarators.

**Comment by dwgoon** [comment]
Thanks for letting me know this issue. Could you please make a pull request?

**Comment by detrin** [comment]
I had the same issue, and I solved it in the same manner. I am happy to create a pull request. However there won't pre probably immediate fix, but I will try to find some time in next 48 hours. Would you assign me this issue?

**Comment by detrin** [comment]
Also, I wonder why this package is not on PyPi registry?

**Comment by detrin** [comment]
This might be helpful in future. https://github.com/dwgoon/jpegio/compare/master...EldritchJS:jpegio:master

**Comment by detrin** [comment]
OKay so I was fixing things without the fork on my own, then run into the issue with JPEG_LIB_VERSION. Seems like almost all of the issues were solved in the fork. So, I just created PR into develop and it seems that the installation and tests are finally running again.

```shell
pip install -e .
python -m unittest tests
```
with python
```
~/Documents/projects/jpegio develop ❯ python                                                                                                                                                                  Py jpegio
Python 3.10.6 (main, Aug 18 2022, 19:43:30) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

If it looks good to you @dwgoon I would create another release. The PyPI name is unfortunately taken by @EldritchJS. Not sure if I can tag him, I will create issue in his repository asking whether he could release the name to us, since this is the original repository and he has only fork. If he won't comply I would perhaps use some prefix like py-jpegio.

@martinbenes1996 Please could you use develop branch for testing if it works for you now?

**Comment by detrin** [comment]
This is the PyPI package https://pypi.org/project/jpegio/

**Comment by EldritchJS** [comment]
@detrin I'll get the PyPi name released, no problem

**Comment by EldritchJS** [comment]
@dwgoon @detrin I can add you both as collaborators/owners to the PyPi project, will that work? Let me know your PyPi usernames if so.

**Comment by detrin** [comment]
> @dwgoon @detrin I can add you both as collaborators/owners to the PyPi project, will that work? Let me know your PyPi usernames if so.

Awesome! It has been years since I used last time PyPi for publishing anything. I have created new account https://pypi.org/user/detrin/. According to https://discuss.python.org/t/transferring-a-pypi-name-to-someone-else/7196 you are right, it is not possible to transfer ownership. 

I suggest having us all three as owner until there is new release. I would leave it then to @dwgoon to make decision on how he wishes the collaboration continues, in the end it is his repo. I would like to make it functional again.

**Comment by detrin** [comment]
@martinbenes1996 I see you used temporal workaround https://github.com/martinbenes1996/jpeglib/blob/3861c46093a48d385288a42f032fd9fdf3f9fe1a/.github/common/install_test_dependencies/action.yml#L28

**Comment by detrin** [comment]
@EldritchJS btw the build-system tag in pyproject.toml is nice! I removed the required dependency cython for build in setup.py https://github.com/dwgoon/jpegio/commit/198d5764bf4187e2106f5f43ebc8e6e967ae80f6

**Comment by EldritchJS** [comment]
@detrin You have a collab invite on PyPi now. I agree the ultimate decision should be left to @dwgoon (especially if it's desired to have the PyPi package updated via Github actions or othersise) but for now you'll be able to incorporate your changes and this package can be made functional.

**Comment by detrin** [comment]
> @detrin You have a collab invite on PyPi now. I agree the ultimate decision should be left to @dwgoon (especially if it's desired to have the PyPi package updated via Github actions or otherwise) but for now you'll be able to incorporate your changes and this package can be made functional.

thanks, I suggest then waiting for his reply

**Comment by dwgoon** [comment]
@EldritchJS Thanks for your suggestion. To make things easier, it would be better to give this repository a different PyPi release name.

@detrin Thanks for your critical contribution. What if we name the PyPi release of this repo **pyjpegio**?

**Comment by detrin** [comment]
> @EldritchJS Thanks for your suggestion. To make things easier, it would be better to give this repository a different PyPi release name.
> 
> @detrin Thanks for your critical contribution. What if we name the PyPi release of this repo **pyjpegio**?

** pyjpegio** is fine from my side, we shall ping all the users of this repository, so that they know they don't have to clone the repository anymore. Do you want to create PyPi project, or do you want me to do that?

**Comment by dwgoon** [comment]
@detrin Thanks for your quick response. I will deploy the wheels on the PyPi server soon :)

**Comment by detrin** [comment]
https://github.com/dwgoon/jpegio/pull/27 @dwgoon  please have a look at this MR

**Comment by detrin** [comment]
Closing as it is solved by https://github.com/dwgoon/jpegio/pull/27
